/**
 * Do not edit directly, this file was auto-generated.
 */

export const PrimitiveWhite = "#ffffff"; // Pure white — base background
export const PrimitiveBlack = "#111111"; // Near-black — base text
export const PrimitiveTerracotta60 = "#c4633d"; // Terracotta light — pressed state rebound
export const PrimitiveTerracotta100 = "#a63d1f"; // Brand accent — the only accent color
export const PrimitiveTerracotta140 = "#66fa17"; // Terracotta dark — hover state
export const PrimitiveGray100 = "#f5f5f5"; // Light surface — card and section backgrounds
export const PrimitiveBorderDefault = "#e5e5e5"; // Subtle border — visual equivalent of rgba(0,0,0,0.1)
export const PrimitiveGreen100 = "#2d6a4f"; // Success — muted green
export const PrimitiveYellow100 = "#8b7a3f"; // Warning — warm amber
export const PrimitiveRed100 = "#8b1a1a"; // Error — distinct from terracotta
export const PrimitiveBlue100 = "#2d4a7a"; // Info — calm blue
export const Space1 = "4px"; // Base unit
export const Space2 = "8px"; // Inline gaps
export const Space3 = "12px"; // Sub-element spacing
export const Space4 = "16px"; // Standard component padding
export const Space6 = "24px"; // Card padding
export const Space8 = "32px"; // Component-to-component gap
export const Space10 = "40px"; // Large component spacing
export const Space12 = "48px"; // Section breaks
export const Space16 = "64px"; // Layout whitespace
export const Space20 = "80px"; // Page section padding
export const Space24 = "96px"; // Hero-level spacing
export const RadiusNone = "0px"; // No radius
export const RadiusSm = "4px"; // Tags, chips
export const RadiusMd = "8px"; // Cards, modals
export const RadiusLg = "16px"; // Large surfaces
export const RadiusFull = "999px"; // Pills — all buttons
export const RadiusButton = "999px"; // Pill buttons — locked
export const RadiusCard = "16px"; // Card corners
export const RadiusTag = "999px"; // Tag pills
export const RadiusInput = "8px"; // Input fields
export const ShadowSm = "0 1px 3px rgba(0,0,0,0.10)"; // Subtle containment
export const ShadowMd = "0 4px 6px rgba(0,0,0,0.10)"; // Dropdowns
export const ShadowLg = "0 10px 15px rgba(0,0,0,0.10)"; // Modals
export const ShadowCardHover = "0 8px 30px rgba(0,0,0,0.12)"; // Card hover
export const ShadowFocus = "0 0 0 2px #111111"; // Focus ring
export const DurationFast = "100ms"; // Hover transitions
export const DurationNormal = "200ms"; // State changes
export const DurationModerate = "300ms"; // Modals, panels
export const DurationSlow = "500ms"; // Page transitions
export const ColorBgDefault = "#ffffff"; // Page background
export const ColorBgHover = "#a63d1f0f"; // Interactive card hover tint
export const ColorTextPrimary = "#111111"; // All text — never muted
export const ColorTextHover = "#66fa17"; // Nav links on hover
export const ColorSurfaceDefault = "#f5f5f5"; // Card backgrounds
export const ColorBorderDefault = "#e5e5e5"; // Dividers, card borders
export const ColorBorderHover = "#a63d1f"; // Card bottom border on hover
export const ColorAccentDefault = "#a63d1f"; // Primary accent — one per viewport
export const ColorAccentHover = "#66fa17"; // Hover — darker
export const ColorAccentPressed = "#c4633d"; // Pressed — lighter rebound
export const ColorFeedbackSuccess = "#2d6a4f"; // Confirmation
export const ColorFeedbackSuccessBg = "#2d6a4f14"; // Success background
export const ColorFeedbackWarning = "#8b7a3f"; // Caution
export const ColorFeedbackWarningBg = "#92711a14"; // Warning background
export const ColorFeedbackError = "#8b1a1a"; // Error
export const ColorFeedbackErrorBg = "#8b1a1a14"; // Error background
export const ColorFeedbackInfo = "#2d4a7a"; // Informational
export const ColorFeedbackInfoBg = "#2d4a7a14"; // Info background
export const SpacingInlineXs = "4px"; // Icon to label
export const SpacingInlineSm = "8px"; // Inline gap
export const SpacingInlineMd = "16px"; // Standard inline padding
export const SpacingInlineLg = "24px"; // Wide inline — nav links
export const SpacingStackXs = "8px"; // Tight vertical
export const SpacingStackSm = "16px"; // Related elements
export const SpacingStackMd = "24px"; // Card internal
export const SpacingStackLg = "32px"; // Component-to-component
export const SpacingStackXl = "48px"; // Section break
export const SpacingLayoutSection = "80px"; // Between sections
export const SpacingLayoutHero = "96px"; // Hero padding
export const SpacingLayoutContent = "64px"; // Layout whitespace
export const ElevationFlat = "none"; // DL_ default
export const ElevationDropdown = "0 4px 6px rgba(0,0,0,0.10)"; // Dropdowns
export const ElevationModal = "0 10px 15px rgba(0,0,0,0.10)"; // Modals
export const ElevationCardHover = "0 8px 30px rgba(0,0,0,0.12)"; // Card hover
export const ElevationFocus = "0 0 0 2px #111111"; // Focus ring
